### ISSUE TITLE
Benchmark against pure Julia einsum?

### ISSUE THREAD

**Issue by Moelf** [UB-Quantic/OptimizedEinsum.jl#3]
For example, Tullio.jl

**Comment by mofeing** [comment]
Well, for me, benchmarks make sense in order to compare the efficiency of different implementations of the same algorithm, or complexity of different algorithms. But the focus of `opt_einsum` is different.

It offers a generic interface for contraction path algorithms and already implements some of them: greedy, random greedy, branch, ... These heuristic algorithms are of use when the tensor network is large as they can handle thousands of tensors, sometimes finding quasioptimal paths.

So while Tullio, TensorOperations, OMEinsum, ... are focused on small _einsum_ expressions and squeezing every bit from it, OptimizedEinsum's focus are heuristic algorithms for large _einsum_ expressions.

In my mind, it makes more sense that other _einsum_ libraries call OptimizedEinsum so comparison would be complicated. But sure, you can run `contract` and it should work, but implementation should be suboptimal currently as it translates `Array`s into `np.ndarray`s and run them in Python.

My wish is to change this and have a pure Julia implementation (or at least of the `contract` method) but this will progress step by step. I can offer a _einsum_ macro in the future but this is not critical as I'm more interested on finding contraction paths dynamically.
